// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsgnijsmhfceqdtifcjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZ25panNtaGZjZXFkdGlmY2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTI5MzMsImV4cCI6MjA2MzUyODkzM30.UIITCko7NT-nYrnpD-ZuRSjKFQPZOhCkNP_Z7GpfMZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);